services:
    auth:
        container_name: auth-svc
        build:
            context: .
            dockerfile: ./apps/auth/Dockerfile
        ports:
            - 8001:8001
        env_file:
            - ./apps/auth/.env.prod
        networks:
            - event-reward-network
    event:
        container_name: event-svc
        build:
            context: .
            dockerfile: ./apps/event/Dockerfile
        ports:
            - 8002:8002
        env_file:
            - ./apps/event/.env.prod
        networks:
            - event-reward-network
    gateway:
        container_name: gateway-svc
        build:
            context: .
            dockerfile: ./apps/gateway/Dockerfile
        ports:
            - 8000:8000
        env_file:
            - ./apps/gateway/.env.prod
        networks:
            - event-reward-network
        depends_on:
            - auth
            - event

networks:
    event-reward-network:
        external: true
